github: [jeffersondev]
patreon: jeffersonmusic
open_collective: jefferson-guitar-project
ko_fi: jeffersondev
tidelift: npm/jefferson-pedalboard
community_bridge: cloud-foundry
liberapay: jeffersondev
issuehunt: jeffersondev
lfx_crowdfunding: cloud-foundry
polar: jeffersondev
buy_me_a_coffee: jeffersondev
thanks_dev: jeffersondev
custom: ['https://jefferson.dev/sponsor', 'https://paypal.me/jeffersondev']
